name: sudosh2
on: push
jobs:
  build_pkg:
    uses: gardenlinux/package-build/.github/workflows/build_pkg.yml@main
    with:
      source: git+https://github.com/squash/sudosh2
      debian_source: native
      git_filter: v[0-9\.]*$
      git_tag_match: v([0-9\-]*)
